
load_yaml: True
gpu: '0'

# pretraining setting
continue_train: False
# continue_train: True
ckpt_name: 'model_best.pth.tar'

# # dataset
# data_type: 'pair'
# # data_type: 'single'
# dataset_name: 'ADNI'
# # data_path: '../data/ADNI/'
# data_path: '../../longitudinal-social-pooling/data/ADNI/'
# img_file_name: 'ADNI_longitudinal_img_aug.h5'
# noimg_file_name: 'ADNI_longitudinal_noimg.h5'
# subj_list_postfix: 'NC_AD_pMCI_sMCI'
# # subj_list_postfix: 'NC_AD'
# # subj_list_postfix: 'pMCI_sMCI'

data_type: 'pair'
dataset_name: 'CP'
img_size: 64 #one number which represents all dimensions
# data_format: 'uncrop_128' #cropped image; crop; or uncropped images: uncrop
# data_path: '../data/LAB/'
data_path: '/media/andjela/SeagatePor1/LSSL/data/uncrop_64'
img_file_name: 'CP_longitudinal_img.h5'
noimg_file_name: 'CP_longitudinal_noimg.h5'
# subj_list_postfix: 'C_single'
subj_list_postfix: 'C'
# subj_list_postfix: 'C_E_HE'0

# data_type: 'pair'
# dataset_name: 'NCANDA'
# data_path: '../data/NCANDA/'
# img_file_name: 'NCANDA_longitudinal_img_aug.h5'
# noimg_file_name: 'NCANDA_longitudinal_noimg.h5'
# subj_list_postfix: 'all'

# training setting
epochs: 450
batch_size: 2 #32 #64
num_fold: 5
fold: 2
shuffle: True
lr: 0.0001
aug: False

# model setting
latent_size: 1024
inter_num_ch: 64
num_neighbours: 5
agg_method: 'gaussian'
# N_km: [120, 60, 30] #[N/5, N/10, N/20] where N is the number of subjects
N_km: [12, 6, 3]
# N_km: [6, 3]
postpone_proto: 10 #20

model_name: 'AE'
# model_name: 'VAE'
# model_name: 'LSSL'
# model_name: 'LSP'       # longitudinal social pooling
lambda_recon: 2.
lambda_dir: 0.
lambda_dis: 0.
lambda_cls: 0.
lambda_kl: 0.
lambda_nce: 0.
lambda_proto: 0.

# lambda_dir: 1.
# lambda_dis: 0.
# lambda_cls: 0.
# lambda_kl: 0.
# lambda_nce: 0.
# lambda_proto: 1.
